### ISSUE TITLE
Build GRU model class

### ISSUE THREAD

**Issue by rwblickhan** [ubclaunchpad/mimic#19]
Build a model class for the GRU RNN.

**Comment by rwblickhan** [comment]
Blocked on #18 - we should decide if this is beneficial/feasible first.

**Comment by rwblickhan** [comment]
It looks like this is included in Keras, so it shouldn't be particularly difficult to build.

**Comment by frankfka** [comment]
Here's a tutorial with shakespeare text: https://www.tensorflow.org/tutorials/sequences/text_generation

**Comment by rwblickhan** [comment]
Closed by #59.
