### ISSUE TITLE
Set up logging and switch over print statements

### ISSUE THREAD

**Issue by rwblickhan** [ubclaunchpad/mimic#27]
There's a few instances of `print` statements in the code base. Since we want this to be used as a library or possibly as an API, we'll want these to be "real" logging statements, e.g. with the `logging` module provided by the standard library.

**Comment by r614** [comment]
I was wondering if you want the log file to reinstatiate each run and wipe everything from previous runs, or append to the log file upon each run?

**Comment by rwblickhan** [comment]
We should probably make it configurable, so the user of the library can decide what they want to do - they may not even want a log file but instead have it routed to standard output.

**Comment by r614** [comment]
We could add a separate method to the base model class to configure logging? Implementation should be similar throughout all model classes so I think it should be fine?

**Comment by rwblickhan** [comment]
Closed by #48.
