### ISSUE TITLE
Find translation dataset

### ISSUE THREAD

**Issue by rwblickhan** [ubclaunchpad/mimic#43]
Find a dataset we can use for translation, clean it, and save it.

**Comment by jackattackyang** [comment]
Mirroring comments in corresponding PR.
English to Vietnamese dataset from [Stanford](https://nlp.stanford.edu/projects/nmt/). They also have English to German and English to Czech but those are much bigger. 
Also this [site](https://machinelearningmastery.com/prepare-french-english-dataset-machine-translation/) contains English to French but it is 200MB.

**Comment by r614** [comment]
Don't know about translation, but this library might help finding more corpus: 

https://www.clips.uantwerpen.be/pattern
