### ISSUE TITLE
Research which ML API to use

### ISSUE THREAD

**Issue by rwblickhan** [ubclaunchpad/mimic#5]
There's a number of different ML APIs, like Caffe, Pytorch, Keras, or even raw TensorFlow, that we need to decide between. Do some research into the pros and cons of each interface, particularly in relation to LSTMs - though do note I would prefer Python if possible. Please put any comments into this issue.

**Comment by jackattackyang** [comment]
Just from general Googling around, Keras with Tensorflow is the best option. 
Some sources: 
- [What is the best Neural Network Library](https://www.quora.com/What-is-the-best-neural-network-library-for-Python)
- [Reddit post: "TF for RNN, PyTorch for conv"](https://www.reddit.com/r/MachineLearning/comments/7ziagd/d_discussion_on_pytorch_vs_tensorflow/)
- [Another Reddit post confirming more support for RNN in TF](https://www.reddit.com/r/learnmachinelearning/comments/6a1hl2/pytorch_vs_tensorflow_which_one_do_you_use_and_why/)

**Comment by rwblickhan** [comment]
Sounds good, we'll use Keras/TF then.
